version: '3'

services:
    mysql:
        platform: linux/x86_64
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: subscription_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: secret
        ports:
            - '3308:3306'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 10s
            retries: 10
    api:
        container_name: api
        build: .
        restart: always
        ports:
            - '7777:3000'
        volumes:
            - .:/app
            - /app/node_modules
            - /app/dist
        depends_on:
            mysql:
                condition: service_healthy
        links:
            - mysql

    admin:
        image: adminer
        ports:
            - '8080:8080'
